server:
  context-path: /brewer
spring:
  application:
    name: brewer
  http:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
  resources:
    static-locations:
    - classpath:/static/
