flyway:
  url: jdbc:mysql://localhost:3306/brewer?autoReconnect=true&useSSL=false
  user: root
  password: admin
server:
  context-path: /brewer
spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/brewer?autoReconnect=true&useSSL=false
    username: root
    password: admin
    tomcat:
      initial-size: 5
      max-active: 5
      min-idle: 5
      max-idle: 5
  application:
    name: brewer
  http:
    encoding:
      force: true
      enabled: true
      charset: UTF-8
  resources:
    static-locations:
    - classpath:/static/
  mvc:
    favicon:
      enabled: true
